# Generated by Django 3.1.4 on 2021-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210406_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
