# Generated by Django 3.2.4 on 2021-06-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
