# Generated by Django 3.2.4 on 2021-06-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0002_alter_coordinates_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='ludo.player'),
        ),
    ]
