# Generated by Django 3.2.4 on 2021-06-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0003_alter_coordinates_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='reached',
            field=models.BooleanField(default=False),
        ),
    ]
