# Generated by Django 3.2.4 on 2021-06-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0005_auto_20210617_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='runnerup1r',
            new_name='runnerup2',
        ),
    ]
