# Generated by Django 3.2.4 on 2021-06-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0006_rename_runnerup1r_game_runnerup2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='ludo.game')),
            ],
        ),
    ]
