# Generated by Django 3.2.4 on 2021-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0007_gametoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
