# Generated by Django 3.1.4 on 2021-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=30)),
                ('dayId', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('link', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
