# Generated by Django 3.1.4 on 2021-06-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='day',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='dayId',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('dayId', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lecture')),
            ],
        ),
    ]
