# Generated by Django 3.1.4 on 2021-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
