# Generated by Django 3.1.4 on 2021-04-22 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 22, 55, 25, 471950)),
        ),
    ]
