# Generated by Django 3.2.4 on 2021-07-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnerId', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(default='', max_length=40)),
                ('runnerup1', models.CharField(default='', max_length=40)),
                ('runnerup2', models.CharField(default='', max_length=40)),
                ('loser', models.CharField(default='', max_length=40)),
                ('ended', models.BooleanField(default=False)),
                ('turn', models.IntegerField(default=0)),
                ('No_of_players', models.IntegerField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('turn', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=30)),
                ('colorId', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='onlineLudo.onlinegame')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineGameToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='onlineLudo.onlinegame')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='log', max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs', to='onlineLudo.onlinegame')),
            ],
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField()),
                ('x', models.IntegerField()),
                ('number', models.IntegerField()),
                ('initial', models.BooleanField(default=True)),
                ('reached', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='onlineLudo.onlineplayer')),
            ],
        ),
    ]
