# Generated by Django 3.2.4 on 2021-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineplayer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlineplayer',
            name='token',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='coord',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coord',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
