# Generated by Django 3.2.4 on 2021-07-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0003_alter_onlineplayer_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineplayer',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
