# Generated by Django 3.2.4 on 2021-07-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0004_onlineplayer_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinegame',
            name='No_of_players',
        ),
    ]
