# Generated by Django 3.2.4 on 2021-07-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0005_remove_onlinegame_no_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineplayer',
            name='lastTurn',
            field=models.IntegerField(default=-1),
        ),
    ]
