# Generated by Django 3.2.4 on 2021-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0006_onlineplayer_lastturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineplayer',
            name='lastTurn',
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='lastTurn',
            field=models.IntegerField(default=-1),
        ),
    ]
