# Generated by Django 3.2.4 on 2021-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0007_auto_20210707_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineplayer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
