# Generated by Django 3.2.4 on 2021-07-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0009_onlineplayer_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineplayer',
            name='needsteps',
            field=models.BooleanField(default=False),
        ),
    ]
