# Generated by Django 3.2.4 on 2021-07-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0011_auto_20210710_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='dice',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onlineLudo.onlinegame')),
            ],
        ),
    ]
