# Generated by Django 3.2.4 on 2021-07-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0012_auto_20210712_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegame',
            name='old',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='onlineLudo.oldcoordinate'),
        ),
    ]
