# Generated by Django 3.2.4 on 2021-07-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0013_onlinegame_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinegame',
            name='old',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineLudo.oldcoordinate'),
        ),
    ]
