# Generated by Django 3.2.4 on 2021-07-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0014_alter_onlinegame_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineplayer',
            name='refresh',
            field=models.BooleanField(default=False),
        ),
    ]
