# Generated by Django 3.2.4 on 2021-07-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0015_onlineplayer_refresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorId', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='lastplayed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineLudo.lastplayed'),
        ),
    ]
