# Generated by Django 3.2.4 on 2021-07-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLudo', '0016_auto_20210714_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='game',
        ),
        migrations.RemoveField(
            model_name='onlinegame',
            name='old',
        ),
        migrations.DeleteModel(
            name='OldCoordinate',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
