# Generated by Django 3.1.4 on 2021-06-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claySchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='claySchedule.Day'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='claySchedule.time'),
        ),
    ]
