# Generated by Django 3.1.4 on 2021-06-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claySchedule', '0005_auto_20210605_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('teacher', models.CharField(default='', max_length=40)),
                ('duration', models.IntegerField()),
                ('link', models.CharField(max_length=150)),
                ('time', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='claySchedule.time')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('dayId', models.IntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='claySchedule.lecture')),
            ],
        ),
    ]
