# Generated by Django 3.2.4 on 2021-06-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claySchedule', '0006_day_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
