# Generated by Django 3.2.4 on 2021-06-05 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claySchedule', '0007_auto_20210605_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('dayId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('teacher', models.CharField(default='', max_length=40)),
                ('duration', models.IntegerField()),
                ('link', models.CharField(max_length=150)),
                ('day', models.ManyToManyField(blank=True, related_name='lectures', to='claySchedule.Day')),
                ('time', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='claySchedule.time')),
            ],
        ),
    ]
